# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Copyright (C) 2000 MySQL AB & MySQL Finland AB & TCX DataKonsult AB
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# This file is public domain and comes with NO WARRANTY of any kind


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = x86_64-pc-linux-gnuoldld
build_triplet = x86_64-pc-linux-gnuoldld
host_alias = x86_64-pc-linux-gnuoldld
host_triplet = x86_64-pc-linux-gnuoldld
target_alias = x86_64-pc-linux-gnuoldld
target_triplet = x86_64-pc-linux-gnuoldld
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -g -pg -ggdb3  -DDBUG_ON -DSAFE_MUTEX -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP 
CHARSETS_NEED_SOURCE =  latin1
CHARSET_OBJS = 
CHARSET_SRCS = 
CHECK_PID = /usr/bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /usr/bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure  --with-debug=yes
CP = /usr/bin/cp
CPP = gcc -E
CXX = c++
CXXFLAGS = -g -pg -ggdb3  -DSAFE_MUTEX -m32  -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /usr/bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /usr/bin/hostname
IS_LINUX = true
KILL = /usr/bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /usr/bin/ln
LN_CP_F = /usr/bin/ln -s
LN_S = ln -s
MACHINE_TYPE = x86_64
MAINT = #
MAKEINFO = makeinfo
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /usr/bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.49
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32349
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/local/bin/perl
PERL5 = /usr/local/bin/perl
PROTOCOL_VERSION = 10
PS = /usr/bin/ps
RANLIB = ranlib
RM = /usr/bin/rm
SAVE_CFLAGS = -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
SAVE_CXXFLAGS = -m32
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /usr/bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnuoldld
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.49
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /usr/bin/uname

INCLUDES = -I$(srcdir)/../include 				-I../include -I$(srcdir)/.. -I$(top_srcdir) 				-I..

LIBS = -lz -lcrypt -lnsl -lm 
LDADD =  ../libmysql/libmysqlclient.la
bin_PROGRAMS = mysql mysqladmin mysqlcheck mysqlshow  mysqldump mysqlimport mysqltest mysqlbinlog

noinst_PROGRAMS = insert_test select_test thread_test
noinst_HEADERS = sql_string.h completion_hash.h my_readline.h 				client_priv.h

mysql_SOURCES = mysql.cc readline.cc sql_string.cc completion_hash.cc
mysql_LDADD = $(top_builddir)/readline/libreadline.a -lncurses $(LDADD) $(CXXLDFLAGS)
mysqlbinlog_LDADD = $(LDADD) $(CXXLDFLAGS)
mysql_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqladmin_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqlcheck_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqlshow_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqldump_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqlimport_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
insert_test_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
select_test_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqltest_SOURCES = mysqltest.c
mysqltest_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
mysqlbinlog_SOURCES = mysqlbinlog.cc 
mysqlbinlog_DEPENDENCIES = $(LIBRARIES) $(pkglib_LTLIBRARIES)
sql_src = log_event.h log_event.cc

# Fix for mit-threads
DEFS = -DUNDEF_THREADS_HACK
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
PROGRAMS =  $(bin_PROGRAMS) $(noinst_PROGRAMS)

CPPFLAGS = 
LDFLAGS =  -rdynamic
mysql_OBJECTS =  mysql.o readline.o sql_string.o completion_hash.o
mysql_LDFLAGS = 
mysqladmin_SOURCES = mysqladmin.c
mysqladmin_OBJECTS =  mysqladmin.o
mysqladmin_LDADD = $(LDADD)
mysqladmin_LDFLAGS = 
mysqlcheck_SOURCES = mysqlcheck.c
mysqlcheck_OBJECTS =  mysqlcheck.o
mysqlcheck_LDADD = $(LDADD)
mysqlcheck_LDFLAGS = 
mysqlshow_SOURCES = mysqlshow.c
mysqlshow_OBJECTS =  mysqlshow.o
mysqlshow_LDADD = $(LDADD)
mysqlshow_LDFLAGS = 
mysqldump_SOURCES = mysqldump.c
mysqldump_OBJECTS =  mysqldump.o
mysqldump_LDADD = $(LDADD)
mysqldump_LDFLAGS = 
mysqlimport_SOURCES = mysqlimport.c
mysqlimport_OBJECTS =  mysqlimport.o
mysqlimport_LDADD = $(LDADD)
mysqlimport_LDFLAGS = 
mysqltest_OBJECTS =  mysqltest.o
mysqltest_LDADD = $(LDADD)
mysqltest_LDFLAGS = 
mysqlbinlog_OBJECTS =  mysqlbinlog.o
mysqlbinlog_LDFLAGS = 
insert_test_SOURCES = insert_test.c
insert_test_OBJECTS =  insert_test.o
insert_test_LDADD = $(LDADD)
insert_test_LDFLAGS = 
select_test_SOURCES = select_test.c
select_test_OBJECTS =  select_test.o
select_test_LDADD = $(LDADD)
select_test_LDFLAGS = 
thread_test_SOURCES = thread_test.c
thread_test_OBJECTS =  thread_test.o
thread_test_LDADD = $(LDADD)
thread_test_DEPENDENCIES =  ../libmysql/libmysqlclient.la
thread_test_LDFLAGS = 
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(mysql_SOURCES) mysqladmin.c mysqlcheck.c mysqlshow.c mysqldump.c mysqlimport.c $(mysqltest_SOURCES) $(mysqlbinlog_SOURCES) insert_test.c select_test.c thread_test.c
OBJECTS = $(mysql_OBJECTS) mysqladmin.o mysqlcheck.o mysqlshow.o mysqldump.o mysqlimport.o $(mysqltest_OBJECTS) $(mysqlbinlog_OBJECTS) insert_test.o select_test.o thread_test.o

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cc .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps client/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

mysql: $(mysql_OBJECTS) $(mysql_DEPENDENCIES)
	@rm -f mysql
	$(CXXLINK) $(mysql_LDFLAGS) $(mysql_OBJECTS) $(mysql_LDADD) $(LIBS)

mysqladmin: $(mysqladmin_OBJECTS) $(mysqladmin_DEPENDENCIES)
	@rm -f mysqladmin
	$(LINK) $(mysqladmin_LDFLAGS) $(mysqladmin_OBJECTS) $(mysqladmin_LDADD) $(LIBS)

mysqlcheck: $(mysqlcheck_OBJECTS) $(mysqlcheck_DEPENDENCIES)
	@rm -f mysqlcheck
	$(LINK) $(mysqlcheck_LDFLAGS) $(mysqlcheck_OBJECTS) $(mysqlcheck_LDADD) $(LIBS)

mysqlshow: $(mysqlshow_OBJECTS) $(mysqlshow_DEPENDENCIES)
	@rm -f mysqlshow
	$(LINK) $(mysqlshow_LDFLAGS) $(mysqlshow_OBJECTS) $(mysqlshow_LDADD) $(LIBS)

mysqldump: $(mysqldump_OBJECTS) $(mysqldump_DEPENDENCIES)
	@rm -f mysqldump
	$(LINK) $(mysqldump_LDFLAGS) $(mysqldump_OBJECTS) $(mysqldump_LDADD) $(LIBS)

mysqlimport: $(mysqlimport_OBJECTS) $(mysqlimport_DEPENDENCIES)
	@rm -f mysqlimport
	$(LINK) $(mysqlimport_LDFLAGS) $(mysqlimport_OBJECTS) $(mysqlimport_LDADD) $(LIBS)

mysqltest: $(mysqltest_OBJECTS) $(mysqltest_DEPENDENCIES)
	@rm -f mysqltest
	$(LINK) $(mysqltest_LDFLAGS) $(mysqltest_OBJECTS) $(mysqltest_LDADD) $(LIBS)

mysqlbinlog: $(mysqlbinlog_OBJECTS) $(mysqlbinlog_DEPENDENCIES)
	@rm -f mysqlbinlog
	$(CXXLINK) $(mysqlbinlog_LDFLAGS) $(mysqlbinlog_OBJECTS) $(mysqlbinlog_LDADD) $(LIBS)

insert_test: $(insert_test_OBJECTS) $(insert_test_DEPENDENCIES)
	@rm -f insert_test
	$(LINK) $(insert_test_LDFLAGS) $(insert_test_OBJECTS) $(insert_test_LDADD) $(LIBS)

select_test: $(select_test_OBJECTS) $(select_test_DEPENDENCIES)
	@rm -f select_test
	$(LINK) $(select_test_LDFLAGS) $(select_test_OBJECTS) $(select_test_LDADD) $(LIBS)

thread_test: $(thread_test_OBJECTS) $(thread_test_DEPENDENCIES)
	@rm -f thread_test
	$(LINK) $(thread_test_LDFLAGS) $(thread_test_OBJECTS) $(thread_test_LDADD) $(LIBS)
.cc.o:
	$(CXXCOMPILE) -c $<
.cc.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = client

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
completion_hash.o: completion_hash.cc ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h completion_hash.h
insert_test.o: insert_test.c ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h
mysql.o: mysql.cc client_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/errmsg.h \
	../include/my_dir.h my_readline.h sql_string.h \
	../readline/readline.h ../readline/rlstdc.h \
	../readline/keymaps.h ../readline/chardefs.h \
	../readline/tilde.h completion_hash.h ../include/sslopt-vars.h \
	../include/sslopt-longopts.h ../include/sslopt-usage.h \
	../include/sslopt-case.h
mysqladmin.o: mysqladmin.c client_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/errmsg.h \
	../include/sslopt-vars.h ../include/sslopt-longopts.h \
	../include/sslopt-case.h ../include/sslopt-usage.h
mysqlbinlog.o: mysqlbinlog.cc client_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/errmsg.h log_event.h \
	log_event.cc
mysqlcheck.o: mysqlcheck.c client_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/errmsg.h \
	../include/mysqld_error.h ../include/sslopt-vars.h \
	../include/sslopt-longopts.h ../include/sslopt-usage.h \
	../include/sslopt-case.h
mysqldump.o: mysqldump.c ../include/my_global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/m_string.h \
	client_priv.h ../include/global.h ../include/mysql.h \
	../include/mysql_com.h ../include/mysql_version.h \
	../include/errmsg.h ../include/mysqld_error.h \
	../include/sslopt-vars.h ../include/sslopt-longopts.h \
	../include/sslopt-usage.h ../include/sslopt-case.h
mysqlimport.o: mysqlimport.c client_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/errmsg.h \
	../include/sslopt-vars.h ../include/sslopt-longopts.h \
	../include/sslopt-usage.h ../include/sslopt-case.h
mysqlshow.o: mysqlshow.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/m_string.h \
	../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/mysqld_error.h \
	../include/sslopt-vars.h ../include/sslopt-longopts.h \
	../include/sslopt-usage.h ../include/sslopt-case.h
mysqltest.o: mysqltest.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/m_string.h \
	../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/my_dir.h \
	../include/hash.h ../include/mysqld_error.h \
	../include/violite.h ../include/my_net.h
readline.o: readline.cc ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/m_string.h \
	my_readline.h
select_test.o: select_test.c ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h
sql_string.o: sql_string.cc ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/m_string.h \
	sql_string.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-noinstPROGRAMS \
		mostlyclean-compile mostlyclean-libtool \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-binPROGRAMS clean-noinstPROGRAMS clean-compile \
		clean-libtool clean-tags clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-binPROGRAMS distclean-noinstPROGRAMS \
		distclean-compile distclean-libtool distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-noinstPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


link_sources:
	for f in $(sql_src) ; do \
	  rm -f $(srcdir)/$$f; \
	  /usr/bin/ln -s $(top_srcdir)/sql/$$f $(srcdir)/$$f; \
        done;

thread_test.o:		thread_test.c
			$(COMPILE) -c  $(INCLUDES) $<

# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
