# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Makefile for the GNU readline library.
# Copyright (C) 1994,1996,1997 Free Software Foundation, Inc.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = x86_64-pc-linux-gnuoldld
build_triplet = x86_64-pc-linux-gnuoldld
host_alias = x86_64-pc-linux-gnuoldld
host_triplet = x86_64-pc-linux-gnuoldld
target_alias = x86_64-pc-linux-gnuoldld
target_triplet = x86_64-pc-linux-gnuoldld
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -g -pg -ggdb3  -DDBUG_ON -DSAFE_MUTEX -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP 
CHARSETS_NEED_SOURCE =  latin1
CHARSET_OBJS = 
CHARSET_SRCS = 
CHECK_PID = /usr/bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /usr/bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure  --with-debug=yes
CP = /usr/bin/cp
CPP = gcc -E
CXX = c++
CXXFLAGS = -g -pg -ggdb3  -DSAFE_MUTEX -m32  -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /usr/bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /usr/bin/hostname
IS_LINUX = true
KILL = /usr/bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /usr/bin/ln
LN_CP_F = /usr/bin/ln -s
LN_S = ln -s
MACHINE_TYPE = x86_64
MAINT = #
MAKEINFO = makeinfo
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /usr/bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.49
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32349
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/local/bin/perl
PERL5 = /usr/local/bin/perl
PROTOCOL_VERSION = 10
PS = /usr/bin/ps
RANLIB = ranlib
RM = /usr/bin/rm
SAVE_CFLAGS = -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
SAVE_CXXFLAGS = -m32
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /usr/bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnuoldld
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.49
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /usr/bin/uname

INCLUDES = -I$(srcdir)/../include -I$(srcdir)/.. -I..

noinst_LIBRARIES = libreadline.a

libreadline_a_SOURCES = readline.c funmap.c keymaps.c 			vi_mode.c parens.c rltty.c 			complete.c bind.c isearch.c 			display.c signals.c 			util.c kill.c 			undo.c macro.c input.c 			callback.c terminal.c xmalloc.c 			history.c histsearch.c histexpand.c 			histfile.c nls.c search.c 			shell.c tilde.c 


pkginclude_HEADERS = readline.h chardefs.h keymaps.h history.h tilde.h

noinst_HEADERS = rldefs.h histlib.h rlwinsize.h 			posixstat.h posixdir.h posixjmp.h 			tilde.h rlconf.h rltty.h ansi_stdlib.h 			tcap.h rlstdc.h


EXTRA_DIST = emacs_keymap.c vi_keymap.c

DEFS = -DUNDEF_THREADS_HACK -DHAVE_CONFIG_H
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(noinst_LIBRARIES)

CPPFLAGS = 
LDFLAGS =  -rdynamic
LIBS = -lpthread -lz -lcrypt -lnsl -lm  -lpthread
libreadline_a_LIBADD = 
libreadline_a_OBJECTS =  readline.o funmap.o keymaps.o vi_mode.o \
parens.o rltty.o complete.o bind.o isearch.o display.o signals.o util.o \
kill.o undo.o macro.o input.o callback.o terminal.o xmalloc.o history.o \
histsearch.o histexpand.o histfile.o nls.o search.o shell.o tilde.o
AR = ar
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(noinst_HEADERS) $(pkginclude_HEADERS)

DIST_COMMON =  README COPYING INSTALL Makefile.am Makefile.in configure \
configure.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libreadline_a_SOURCES)
OBJECTS = $(libreadline_a_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps readline/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLIBRARIES:

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

distclean-noinstLIBRARIES:

maintainer-clean-noinstLIBRARIES:

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libreadline.a: $(libreadline_a_OBJECTS) $(libreadline_a_DEPENDENCIES)
	-rm -f libreadline.a
	$(AR) cru libreadline.a $(libreadline_a_OBJECTS) $(libreadline_a_LIBADD)
	$(RANLIB) libreadline.a

install-pkgincludeHEADERS: $(pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkgincludedir)
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(pkgincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(pkgincludedir)/$$p; \
	done

uninstall-pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkgincludedir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = readline

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
bind.o: bind.c ../config.h ../include/getopt.h posixstat.h rldefs.h \
	rlconf.h readline.h rlstdc.h keymaps.h chardefs.h tilde.h \
	history.h
callback.o: callback.c ../config.h rlconf.h rldefs.h readline.h rlstdc.h \
	keymaps.h chardefs.h tilde.h
complete.o: complete.c ../config.h ../include/getopt.h posixdir.h \
	posixstat.h rldefs.h rlconf.h readline.h rlstdc.h keymaps.h \
	chardefs.h tilde.h
display.o: display.c ../config.h ../include/getopt.h posixstat.h \
	rldefs.h rlconf.h tcap.h rltty.h rlwinsize.h readline.h \
	rlstdc.h keymaps.h chardefs.h tilde.h history.h
funmap.o: funmap.c ../config.h rlconf.h readline.h rlstdc.h keymaps.h \
	chardefs.h tilde.h
histexpand.o: histexpand.c ../config.h ../include/getopt.h history.h \
	rlstdc.h histlib.h
histfile.o: histfile.c ../config.h ../include/getopt.h history.h \
	rlstdc.h histlib.h
history.o: history.c ../config.h ../include/getopt.h history.h rlstdc.h \
	histlib.h
histsearch.o: histsearch.c ../config.h ../include/getopt.h history.h \
	rlstdc.h histlib.h
input.o: input.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h
isearch.o: isearch.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
keymaps.o: keymaps.c ../config.h rlconf.h keymaps.h rlstdc.h chardefs.h \
	emacs_keymap.c readline.h tilde.h vi_keymap.c
kill.o: kill.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
macro.o: macro.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
nls.o: nls.c ../config.h ../include/getopt.h rldefs.h rlconf.h
parens.o: parens.c rlconf.h
readline.o: readline.c ../config.h posixstat.h ../include/getopt.h \
	posixjmp.h rldefs.h rlconf.h readline.h rlstdc.h keymaps.h \
	chardefs.h tilde.h history.h
rltty.o: rltty.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	rltty.h rlwinsize.h readline.h rlstdc.h keymaps.h chardefs.h \
	tilde.h
search.o: search.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
shell.o: shell.c ../config.h ../include/getopt.h
signals.o: signals.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
terminal.o: terminal.c ../config.h posixstat.h ../include/getopt.h \
	rldefs.h rlconf.h rltty.h rlwinsize.h tcap.h readline.h \
	rlstdc.h keymaps.h chardefs.h tilde.h history.h
tilde.o: tilde.c ../config.h ../include/getopt.h tilde.h
undo.o: undo.c ../config.h ../include/getopt.h rldefs.h rlconf.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
util.o: util.c ../config.h posixjmp.h ../include/getopt.h rldefs.h \
	rlconf.h readline.h rlstdc.h keymaps.h chardefs.h tilde.h
vi_mode.o: vi_mode.c rlconf.h ../config.h ../include/getopt.h rldefs.h \
	readline.h rlstdc.h keymaps.h chardefs.h tilde.h history.h
xmalloc.o: xmalloc.c ../config.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-pkgincludeHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-pkgincludeHEADERS
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(pkgincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool uninstall-pkgincludeHEADERS \
install-pkgincludeHEADERS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
