# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Copyright (C) 2000 MySQL AB & MySQL Finland AB & TCX DataKonsult AB
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# This file is public domain and comes with NO WARRANTY of any kind


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = x86_64-pc-linux-gnuoldld
build_triplet = x86_64-pc-linux-gnuoldld
host_alias = x86_64-pc-linux-gnuoldld
host_triplet = x86_64-pc-linux-gnuoldld
target_alias = x86_64-pc-linux-gnuoldld
target_triplet = x86_64-pc-linux-gnuoldld
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -g -pg -ggdb3  -DDBUG_ON -DSAFE_MUTEX -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP 
CHARSETS_NEED_SOURCE =  latin1
CHARSET_OBJS = 
CHARSET_SRCS = 
CHECK_PID = /usr/bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /usr/bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure  --with-debug=yes
CP = /usr/bin/cp
CPP = gcc -E
CXX = c++
CXXFLAGS = -g -pg -ggdb3  -DSAFE_MUTEX -m32  -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /usr/bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /usr/bin/hostname
IS_LINUX = true
KILL = /usr/bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /usr/bin/ln
LN_CP_F = /usr/bin/ln -s
LN_S = ln -s
MACHINE_TYPE = x86_64
MAINT = #
MAKEINFO = makeinfo
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /usr/bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.49
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32349
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/local/bin/perl
PERL5 = /usr/local/bin/perl
PROTOCOL_VERSION = 10
PS = /usr/bin/ps
RANLIB = ranlib
RM = /usr/bin/rm
SAVE_CFLAGS = -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
SAVE_CXXFLAGS = -m32
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /usr/bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnuoldld
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.49
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /usr/bin/uname

INCLUDES =  -I$(srcdir)/../include -I../include
pkglib_LIBRARIES = libmystrings.a
#no assembler
#ASRCS = strings-x86.s longlong2str-x86.s
#ASRCS = bmove_upp-sparc.s strappend-sparc.s strend-sparc.s strinstr-sparc.s strmake-sparc.s strmov-sparc.s strnmov-sparc.s strstr-sparc.s strxmov-sparc.s
ASRCS = 
# These file MUST all be on the same line!! Otherwise automake
# generats a very broken makefile
#CSRCS = bfill.c bmove.c bmove512.c bchange.c strxnmov.c int2str.c str2int.c r_strinstr.c atof.c bcmp.c strtol.c strtoul.c strtoll.c strtoull.c strxmov.c bmove_upp.c strappend.c strcont.c strend.c strfill.c strcend.c is_prefix.c strstr.c strinstr.c strmake.c strnmov.c strmov.c longlong2str.c llstr.c ctype.c strnlen.c
#CSRCS = strcont.c strfill.c strcend.c is_prefix.c longlong2str.c bfill.c bmove.c bmove512.c bchange.c strxnmov.c int2str.c str2int.c r_strinstr.c atof.c bcmp.c strtol.c strtoul.c strtoll.c strtoull.c llstr.c ctype.c strnlen.c
CSRCS = strxmov.c bmove_upp.c strappend.c strcont.c strend.c strfill.c strcend.c is_prefix.c strstr.c strinstr.c strmake.c strnmov.c strmov.c longlong2str.c bfill.c bmove.c bmove512.c bchange.c strxnmov.c int2str.c str2int.c r_strinstr.c atof.c bcmp.c strtol.c strtoul.c strtoll.c strtoull.c llstr.c ctype.c strnlen.c

libmystrings_a_SOURCES =  $(ASRCS) $(CSRCS)
noinst_PROGRAMS = conf_to_src
# Default charset definitions
EXTRA_DIST = ctype-big5.c ctype-czech.c ctype-euc_kr.c                         ctype-gb2312.c ctype-gbk.c ctype-sjis.c                         ctype-tis620.c ctype-ujis.c                         ctype_autoconf.c                         strto.c strings-x86.s longlong2str-x86.s 			strxmov.c bmove_upp.c strappend.c strcont.c strend.c 			strfill.c strcend.c is_prefix.c strstr.c strinstr.c 			strmake.c strnmov.c strmov.c strnlen.c 			bmove_upp-sparc.s strappend-sparc.s strend-sparc.s 			strinstr-sparc.s strmake-sparc.s strmov-sparc.s 			strnmov-sparc.s strstr-sparc.s strxmov-sparc.s


OMIT_DEPENDENCIES = pthread.h stdio.h __stdio.h stdlib.h __stdlib.h math.h 			__math.h time.h __time.h unistd.h __unistd.h types.h 			xtypes.h ac-types.h posix.h string.h __string.h 			errno.h socket.h inet.h dirent.h netdb.h 			cleanup.h cond.h debug_out.h fd.h kernel.h mutex.h 			prio_queue.h pthread_attr.h pthread_once.h queue.h 			sleep.h specific.h version.h pwd.h timers.h uio.h 			cdefs.h machdep.h signal.h __signal.h util.h


libmystrings_a_LIBADD = 
conf_to_src_SOURCES = conf_to_src.c
conf_to_src_LDADD = 
#force static linking of conf_to_src - essential when linking against
#custom installation of libc
conf_to_src_LDFLAGS = 
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(pkglib_LIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS =  -rdynamic
LIBS = -lpthread -lz -lcrypt -lnsl -lm  -lpthread
libmystrings_a_DEPENDENCIES = 
#libmystrings_a_OBJECTS =  \
#strings-x86.o \
#longlong2str-x86.o bfill.o \
#bmove.o bmove512.o bchange.o \
#strxnmov.o int2str.o \
#str2int.o r_strinstr.o \
#atof.o bcmp.o strtol.o \
#strtoul.o strtoll.o \
#strtoull.o strxmov.o \
#bmove_upp.o strappend.o \
#strcont.o strend.o strfill.o \
#strcend.o is_prefix.o \
#strstr.o strinstr.o \
#strmake.o strnmov.o strmov.o \
#longlong2str.o llstr.o \
#ctype.o strnlen.o
#libmystrings_a_OBJECTS =  \
#bmove_upp-sparc.o \
#strappend-sparc.o \
#strend-sparc.o \
#strinstr-sparc.o \
#strmake-sparc.o \
#strmov-sparc.o \
#strnmov-sparc.o \
#strstr-sparc.o \
#strxmov-sparc.o strcont.o \
#strfill.o strcend.o \
#is_prefix.o longlong2str.o \
#bfill.o bmove.o bmove512.o \
#bchange.o strxnmov.o \
#int2str.o str2int.o \
#r_strinstr.o atof.o bcmp.o \
#strtol.o strtoul.o strtoll.o \
#strtoull.o llstr.o ctype.o \
#strnlen.o
libmystrings_a_OBJECTS =  \
strxmov.o bmove_upp.o \
strappend.o strcont.o \
strend.o strfill.o \
strcend.o is_prefix.o \
strstr.o strinstr.o \
strmake.o strnmov.o \
strmov.o longlong2str.o \
bfill.o bmove.o bmove512.o \
bchange.o strxnmov.o \
int2str.o str2int.o \
r_strinstr.o atof.o bcmp.o \
strtol.o strtoul.o \
strtoll.o strtoull.o \
llstr.o ctype.o strnlen.o
##libmystrings_a_OBJECTS =  \
##strings-x86.o \
##longlong2str-x86.o bfill.o \
##bmove.o bmove512.o bchange.o \
##strxnmov.o int2str.o \
##str2int.o r_strinstr.o atof.o \
##bcmp.o strtol.o strtoul.o \
##strtoll.o strtoull.o \
##strxmov.o bmove_upp.o \
##strappend.o strcont.o \
##strend.o strfill.o strcend.o \
##is_prefix.o strstr.o \
##strinstr.o strmake.o \
##strnmov.o strmov.o \
##longlong2str.o llstr.o \
##ctype.o strnlen.o
AR = ar
PROGRAMS =  $(noinst_PROGRAMS)

conf_to_src_OBJECTS =  conf_to_src.o
conf_to_src_DEPENDENCIES = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  README ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libmystrings_a_SOURCES) $(conf_to_src_SOURCES)
OBJECTS = $(libmystrings_a_OBJECTS) $(conf_to_src_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps strings/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-pkglibLIBRARIES:

clean-pkglibLIBRARIES:
	-test -z "$(pkglib_LIBRARIES)" || rm -f $(pkglib_LIBRARIES)

distclean-pkglibLIBRARIES:

maintainer-clean-pkglibLIBRARIES:

install-pkglibLIBRARIES: $(pkglib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkglibdir)
	@list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(RANLIB) $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done

uninstall-pkglibLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkglibdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libmystrings.a: $(libmystrings_a_OBJECTS) $(libmystrings_a_DEPENDENCIES)
	-rm -f libmystrings.a
	$(AR) cru libmystrings.a $(libmystrings_a_OBJECTS) $(libmystrings_a_LIBADD)
	$(RANLIB) libmystrings.a

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

conf_to_src: $(conf_to_src_OBJECTS) $(conf_to_src_DEPENDENCIES)
	@rm -f conf_to_src
	$(LINK) $(conf_to_src_LDFLAGS) $(conf_to_src_OBJECTS) $(conf_to_src_LDADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = strings

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
atof.o: atof.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h
bchange.o: bchange.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
bcmp.o: bcmp.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
bfill.o: bfill.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
bmove.o: bmove.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
bmove512.o: bmove512.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
bmove_upp.o: bmove_upp.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
conf_to_src.o: conf_to_src.c ../mit-pthreads/include/endian.h
ctype.o: ctype.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_ctype.h ../include/m_string.h \
	ctype_extra_sources.c ctype_autoconf.c
int2str.o: int2str.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
is_prefix.o: is_prefix.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
llstr.o: llstr.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
longlong2str.o: longlong2str.c ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
r_strinstr.o: r_strinstr.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
str2int.o: str2int.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h ../include/m_ctype.h ../include/my_sys.h \
	../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/raid.h
strappend.o: strappend.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strcend.o: strcend.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strcont.o: strcont.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strend.o: strend.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strfill.o: strfill.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strinstr.o: strinstr.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strmake.o: strmake.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strmov.o: strmov.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strnlen.o: strnlen.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strnmov.o: strnmov.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strstr.o: strstr.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strtol.o: strtol.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h
strtoll.o: strtoll.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strtoul.o: strtoul.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h
strtoull.o: strtoull.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strxmov.o: strxmov.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h
strxnmov.o: strxnmov.c ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/m_string.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-pkglibLIBRARIES
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-pkglibLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(pkglibdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-pkglibLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-pkglibLIBRARIES clean-compile clean-libtool \
		clean-noinstPROGRAMS clean-tags clean-generic \
		mostlyclean-am clean-local

clean: clean-am

distclean-am:  distclean-pkglibLIBRARIES distclean-compile \
		distclean-libtool distclean-noinstPROGRAMS \
		distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-pkglibLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-pkglibLIBRARIES distclean-pkglibLIBRARIES \
clean-pkglibLIBRARIES maintainer-clean-pkglibLIBRARIES \
uninstall-pkglibLIBRARIES install-pkglibLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-noinstPROGRAMS \
distclean-noinstPROGRAMS clean-noinstPROGRAMS \
maintainer-clean-noinstPROGRAMS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean

ctype.o:		ctype_extra_sources.c

ctype_extra_sources.c: conf_to_src
	./conf_to_src $(top_srcdir)  latin1 > \
	              $(srcdir)/ctype_extra_sources.c

# This is because the dependency tracking misses @FOO@ vars in sources.
strtoull.o:		

clean-local:
	rm -f ctype_extra_sources.c

# On Linux gcc can compile the assembly files
#%.o	: %.s
#	$(AS) -o $@ $<

# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
