# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Copyright (C) 2000 MySQL AB & MySQL Finland AB & TCX DataKonsult AB
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = x86_64-pc-linux-gnuoldld
build_triplet = x86_64-pc-linux-gnuoldld
host_alias = x86_64-pc-linux-gnuoldld
host_triplet = x86_64-pc-linux-gnuoldld
target_alias = x86_64-pc-linux-gnuoldld
target_triplet = x86_64-pc-linux-gnuoldld
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -g -pg -ggdb3  -DDBUG_ON -DSAFE_MUTEX -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP 
CHARSETS_NEED_SOURCE =  latin1
CHARSET_OBJS = 
CHARSET_SRCS = 
CHECK_PID = /usr/bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /usr/bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure  --with-debug=yes
CP = /usr/bin/cp
CPP = gcc -E
CXX = c++
CXXFLAGS = -g -pg -ggdb3  -DSAFE_MUTEX -m32  -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /usr/bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /usr/bin/hostname
IS_LINUX = true
KILL = /usr/bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /usr/bin/ln
LN_CP_F = /usr/bin/ln -s
LN_S = ln -s
MACHINE_TYPE = x86_64
MAINT = #
MAKEINFO = makeinfo
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /usr/bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.49
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32349
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/local/bin/perl
PERL5 = /usr/local/bin/perl
PROTOCOL_VERSION = 10
PS = /usr/bin/ps
RANLIB = ranlib
RM = /usr/bin/rm
SAVE_CFLAGS = -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
SAVE_CXXFLAGS = -m32
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /usr/bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnuoldld
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.49
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /usr/bin/uname

INCLUDES =  -I$(srcdir)/../include -I../include 
LDADD =  libnisam.a ../mysys/libmysys.a 			../dbug/libdbug.a ../strings/libmystrings.a

pkglib_LIBRARIES = libnisam.a
bin_PROGRAMS = isamchk isamlog pack_isam
isamchk_DEPENDENCIES = $(LIBRARIES)
isamlog_DEPENDENCIES = $(LIBRARIES)
pack_isam_DEPENDENCIES = $(LIBRARIES)
noinst_PROGRAMS = test1 test2 test3
noinst_HEADERS = isamdef.h
test1_DEPENDENCIES = $(LIBRARIES)
test2_DEPENDENCIES = $(LIBRARIES)
test3_DEPENDENCIES = $(LIBRARIES)
libnisam_a_SOURCES = open.c extra.c info.c rkey.c rnext.c 			_search.c _page.c _key.c _locking.c 			rrnd.c _cache.c _statrec.c _packrec.c 			_dynrec.c update.c write.c delete.c 			rprev.c rfirst.c rlast.c rsame.c rsamepos.c 			panic.c close.c create.c range.c _dbug.c 			log.c changed.c static.c

isamchk_SOURCES = isamchk.c sort.c
CLEANFILES = test?.IS? isam.log
# Omit dependency for ../mit-pthreads/include/ things
OMIT_DEPENDENCIES = pthread.h stdio.h __stdio.h stdlib.h __stdlib.h math.h 			__math.h time.h __time.h unistd.h __unistd.h types.h 			xtypes.h ac-types.h posix.h string.h __string.h 			errno.h socket.h inet.h dirent.h netdb.h 			cleanup.h cond.h debug_out.h fd.h kernel.h mutex.h 			prio_queue.h pthread_attr.h pthread_once.h queue.h 			sleep.h specific.h version.h pwd.h timers.h uio.h 			cdefs.h machdep.h signal.h __signal.h util.h wait.h

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(pkglib_LIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS =  -rdynamic
LIBS = -lpthread -lz -lcrypt -lnsl -lm  -lpthread
libnisam_a_LIBADD = 
libnisam_a_OBJECTS =  open.o extra.o info.o rkey.o rnext.o _search.o \
_page.o _key.o _locking.o rrnd.o _cache.o _statrec.o _packrec.o \
_dynrec.o update.o write.o delete.o rprev.o rfirst.o rlast.o rsame.o \
rsamepos.o panic.o close.o create.o range.o _dbug.o log.o changed.o \
static.o
AR = ar
PROGRAMS =  $(bin_PROGRAMS) $(noinst_PROGRAMS)

isamchk_OBJECTS =  isamchk.o sort.o
isamchk_LDADD = $(LDADD)
isamchk_LDFLAGS = 
isamlog_SOURCES = isamlog.c
isamlog_OBJECTS =  isamlog.o
isamlog_LDADD = $(LDADD)
isamlog_LDFLAGS = 
pack_isam_SOURCES = pack_isam.c
pack_isam_OBJECTS =  pack_isam.o
pack_isam_LDADD = $(LDADD)
pack_isam_LDFLAGS = 
test1_SOURCES = test1.c
test1_OBJECTS =  test1.o
test1_LDADD = $(LDADD)
test1_LDFLAGS = 
test2_SOURCES = test2.c
test2_OBJECTS =  test2.o
test2_LDADD = $(LDADD)
test2_LDFLAGS = 
test3_SOURCES = test3.c
test3_OBJECTS =  test3.o
test3_LDADD = $(LDADD)
test3_LDFLAGS = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libnisam_a_SOURCES) $(isamchk_SOURCES) isamlog.c pack_isam.c test1.c test2.c test3.c
OBJECTS = $(libnisam_a_OBJECTS) $(isamchk_OBJECTS) isamlog.o pack_isam.o test1.o test2.o test3.o

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps isam/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-pkglibLIBRARIES:

clean-pkglibLIBRARIES:
	-test -z "$(pkglib_LIBRARIES)" || rm -f $(pkglib_LIBRARIES)

distclean-pkglibLIBRARIES:

maintainer-clean-pkglibLIBRARIES:

install-pkglibLIBRARIES: $(pkglib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkglibdir)
	@list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(RANLIB) $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done

uninstall-pkglibLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkglibdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libnisam.a: $(libnisam_a_OBJECTS) $(libnisam_a_DEPENDENCIES)
	-rm -f libnisam.a
	$(AR) cru libnisam.a $(libnisam_a_OBJECTS) $(libnisam_a_LIBADD)
	$(RANLIB) libnisam.a

mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

isamchk: $(isamchk_OBJECTS) $(isamchk_DEPENDENCIES)
	@rm -f isamchk
	$(LINK) $(isamchk_LDFLAGS) $(isamchk_OBJECTS) $(isamchk_LDADD) $(LIBS)

isamlog: $(isamlog_OBJECTS) $(isamlog_DEPENDENCIES)
	@rm -f isamlog
	$(LINK) $(isamlog_LDFLAGS) $(isamlog_OBJECTS) $(isamlog_LDADD) $(LIBS)

pack_isam: $(pack_isam_OBJECTS) $(pack_isam_DEPENDENCIES)
	@rm -f pack_isam
	$(LINK) $(pack_isam_LDFLAGS) $(pack_isam_OBJECTS) $(pack_isam_LDADD) $(LIBS)

test1: $(test1_OBJECTS) $(test1_DEPENDENCIES)
	@rm -f test1
	$(LINK) $(test1_LDFLAGS) $(test1_OBJECTS) $(test1_LDADD) $(LIBS)

test2: $(test2_OBJECTS) $(test2_DEPENDENCIES)
	@rm -f test2
	$(LINK) $(test2_LDFLAGS) $(test2_OBJECTS) $(test2_LDADD) $(LIBS)

test3: $(test3_OBJECTS) $(test3_DEPENDENCIES)
	@rm -f test3
	$(LINK) $(test3_LDFLAGS) $(test3_OBJECTS) $(test3_LDADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = isam

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
_cache.o: _cache.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_dbug.o: _dbug.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_dynrec.o: _dynrec.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_key.o: _key.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_locking.o: _locking.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_packrec.o: _packrec.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_page.o: _page.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_search.o: _search.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
_statrec.o: _statrec.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
changed.o: changed.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
close.o: close.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
create.o: create.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
delete.o: delete.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
extra.o: extra.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
info.o: info.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
isamchk.o: isamchk.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h ../include/getopt.h
isamlog.o: isamlog.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h ../include/my_tree.h
log.o: log.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
open.o: open.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
pack_isam.o: pack_isam.c isamdef.h ../include/nisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h ../include/queues.h ../include/my_tree.h \
	../include/mysys_err.h ../include/getopt.h
panic.o: panic.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
range.o: range.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rfirst.o: rfirst.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rkey.o: rkey.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rlast.o: rlast.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rnext.o: rnext.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rprev.o: rprev.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rrnd.o: rrnd.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rsame.o: rsame.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
rsamepos.o: rsamepos.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
sort.o: sort.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h ../include/queues.h
static.o: static.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
test1.o: test1.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
test2.o: test2.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
test3.o: test3.c ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h
update.o: update.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h
write.o: write.c isamdef.h ../include/nisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/thr_lock.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-pkglibLIBRARIES install-binPROGRAMS
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-pkglibLIBRARIES uninstall-binPROGRAMS
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(pkglibdir) $(DESTDIR)$(bindir)


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-pkglibLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-binPROGRAMS \
		mostlyclean-noinstPROGRAMS mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-pkglibLIBRARIES clean-compile clean-libtool \
		clean-binPROGRAMS clean-noinstPROGRAMS clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-pkglibLIBRARIES distclean-compile \
		distclean-libtool distclean-binPROGRAMS \
		distclean-noinstPROGRAMS distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-pkglibLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-binPROGRAMS \
		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-pkglibLIBRARIES distclean-pkglibLIBRARIES \
clean-pkglibLIBRARIES maintainer-clean-pkglibLIBRARIES \
uninstall-pkglibLIBRARIES install-pkglibLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-binPROGRAMS distclean-binPROGRAMS \
clean-binPROGRAMS maintainer-clean-binPROGRAMS uninstall-binPROGRAMS \
install-binPROGRAMS mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS tags \
mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
distdir info-am info dvi-am dvi check check-am installcheck-am \
installcheck install-exec-am install-exec install-data-am install-data \
install-am install uninstall-am uninstall all-redirect all-am all \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Move to automake rules ?
prolint:;	plparse -b -u -hF1 "-width(0,0)" "-format=%f:%l:\s%t:%n\s%m" \
		"-elib(????)" "+elib(?3??)" my.lnt $(nisam_SOURCES)

# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
