# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Copyright (C) 2000 MySQL AB & MySQL Finland AB & TCX DataKonsult AB
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = x86_64-pc-linux-gnuoldld
build_triplet = x86_64-pc-linux-gnuoldld
host_alias = x86_64-pc-linux-gnuoldld
host_triplet = x86_64-pc-linux-gnuoldld
target_alias = x86_64-pc-linux-gnuoldld
target_triplet = x86_64-pc-linux-gnuoldld
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -g -pg -ggdb3  -DDBUG_ON -DSAFE_MUTEX -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP 
CHARSETS_NEED_SOURCE =  latin1
CHARSET_OBJS = 
CHARSET_SRCS = 
CHECK_PID = /usr/bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /usr/bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure  --with-debug=yes
CP = /usr/bin/cp
CPP = gcc -E
CXX = c++
CXXFLAGS = -g -pg -ggdb3  -DSAFE_MUTEX -m32  -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /usr/bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /usr/bin/hostname
IS_LINUX = true
KILL = /usr/bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /usr/bin/ln
LN_CP_F = /usr/bin/ln -s
LN_S = ln -s
MACHINE_TYPE = x86_64
MAINT = #
MAKEINFO = makeinfo
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /usr/bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.49
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32349
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/local/bin/perl
PERL5 = /usr/local/bin/perl
PROTOCOL_VERSION = 10
PS = /usr/bin/ps
RANLIB = ranlib
RM = /usr/bin/rm
SAVE_CFLAGS = -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
SAVE_CXXFLAGS = -m32
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /usr/bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnuoldld
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.49
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /usr/bin/uname

EXTRA_DIST = mi_test_all.sh mi_test_all.res
pkgdata_DATA = mi_test_all mi_test_all.res

INCLUDES =  -I$(srcdir)/../include -I../include 
LDADD =  libmyisam.a ../mysys/libmysys.a 			../dbug/libdbug.a ../strings/libmystrings.a

pkglib_LIBRARIES = libmyisam.a
bin_PROGRAMS = myisamchk myisamlog myisampack
myisamchk_DEPENDENCIES = $(LIBRARIES)
myisamlog_DEPENDENCIES = $(LIBRARIES)
myisampack_DEPENDENCIES = $(LIBRARIES)
noinst_PROGRAMS = mi_test1 mi_test2 mi_test3 ft_test1 ft_eval
noinst_HEADERS = myisamdef.h fulltext.h ftdefs.h ft_test1.h ft_eval.h
mi_test1_DEPENDENCIES = $(LIBRARIES)
mi_test2_DEPENDENCIES = $(LIBRARIES)
mi_test3_DEPENDENCIES = $(LIBRARIES)
ft_test1_DEPENDENCIES = $(LIBRARIES)
ft_eval_DEPENDENCIES = $(LIBRARIES)
libmyisam_a_SOURCES = mi_open.c mi_extra.c mi_info.c mi_rkey.c 			mi_rnext.c mi_rnext_same.c 			mi_search.c mi_page.c mi_key.c mi_locking.c 			mi_rrnd.c mi_scan.c mi_cache.c 			mi_statrec.c mi_packrec.c mi_dynrec.c 			mi_update.c mi_write.c mi_unique.c 			mi_delete.c 			mi_rprev.c mi_rfirst.c mi_rlast.c mi_rsame.c 			mi_rsamepos.c mi_panic.c mi_close.c mi_create.c 			mi_range.c mi_dbug.c mi_checksum.c mi_log.c 			mi_changed.c mi_static.c mi_delete_all.c 			mi_delete_table.c mi_rename.c  mi_check.c 			ft_parser.c ft_search.c ft_stopwords.c ft_static.c 			ft_update.c sort.c

CLEANFILES = test?.MY? FT?.MY? isam.log mi_test_all
DEFS = -DMAP_TO_USE_RAID
# Omit dependency for ../mit-pthreads/include/sys that only exits if
# mit-pthreads are used
OMIT_DEPENDENCIES = pthread.h stdio.h __stdio.h stdlib.h __stdlib.h math.h 			__math.h time.h __time.h unistd.h __unistd.h types.h 			xtypes.h ac-types.h posix.h string.h __string.h 			errno.h socket.h inet.h dirent.h netdb.h 			cleanup.h cond.h debug_out.h fd.h kernel.h mutex.h 			prio_queue.h pthread_attr.h pthread_once.h queue.h 			sleep.h specific.h version.h pwd.h timers.h uio.h 			cdefs.h machdep.h signal.h __signal.h util.h 			wait.h


SUFFIXES = .sh
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(pkglib_LIBRARIES)

CPPFLAGS = 
LDFLAGS =  -rdynamic
LIBS = -lpthread -lz -lcrypt -lnsl -lm  -lpthread
libmyisam_a_LIBADD = 
libmyisam_a_OBJECTS =  mi_open.o mi_extra.o mi_info.o mi_rkey.o \
mi_rnext.o mi_rnext_same.o mi_search.o mi_page.o mi_key.o mi_locking.o \
mi_rrnd.o mi_scan.o mi_cache.o mi_statrec.o mi_packrec.o mi_dynrec.o \
mi_update.o mi_write.o mi_unique.o mi_delete.o mi_rprev.o mi_rfirst.o \
mi_rlast.o mi_rsame.o mi_rsamepos.o mi_panic.o mi_close.o mi_create.o \
mi_range.o mi_dbug.o mi_checksum.o mi_log.o mi_changed.o mi_static.o \
mi_delete_all.o mi_delete_table.o mi_rename.o mi_check.o ft_parser.o \
ft_search.o ft_stopwords.o ft_static.o ft_update.o sort.o
AR = ar
PROGRAMS =  $(bin_PROGRAMS) $(noinst_PROGRAMS)

myisamchk_SOURCES = myisamchk.c
myisamchk_OBJECTS =  myisamchk.o
myisamchk_LDADD = $(LDADD)
myisamchk_LDFLAGS = 
myisamlog_SOURCES = myisamlog.c
myisamlog_OBJECTS =  myisamlog.o
myisamlog_LDADD = $(LDADD)
myisamlog_LDFLAGS = 
myisampack_SOURCES = myisampack.c
myisampack_OBJECTS =  myisampack.o
myisampack_LDADD = $(LDADD)
myisampack_LDFLAGS = 
mi_test1_SOURCES = mi_test1.c
mi_test1_OBJECTS =  mi_test1.o
mi_test1_LDADD = $(LDADD)
mi_test1_LDFLAGS = 
mi_test2_SOURCES = mi_test2.c
mi_test2_OBJECTS =  mi_test2.o
mi_test2_LDADD = $(LDADD)
mi_test2_LDFLAGS = 
mi_test3_SOURCES = mi_test3.c
mi_test3_OBJECTS =  mi_test3.o
mi_test3_LDADD = $(LDADD)
mi_test3_LDFLAGS = 
ft_test1_SOURCES = ft_test1.c
ft_test1_OBJECTS =  ft_test1.o
ft_test1_LDADD = $(LDADD)
ft_test1_LDFLAGS = 
ft_eval_SOURCES = ft_eval.c
ft_eval_OBJECTS =  ft_eval.o
ft_eval_LDADD = $(LDADD)
ft_eval_LDFLAGS = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(pkgdata_DATA)

HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  ChangeLog Makefile.am Makefile.in NEWS TODO


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libmyisam_a_SOURCES) myisamchk.c myisamlog.c myisampack.c mi_test1.c mi_test2.c mi_test3.c ft_test1.c ft_eval.c
OBJECTS = $(libmyisam_a_OBJECTS) myisamchk.o myisamlog.o myisampack.o mi_test1.o mi_test2.o mi_test3.o ft_test1.o ft_eval.o

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s .sh
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps myisam/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-pkglibLIBRARIES:

clean-pkglibLIBRARIES:
	-test -z "$(pkglib_LIBRARIES)" || rm -f $(pkglib_LIBRARIES)

distclean-pkglibLIBRARIES:

maintainer-clean-pkglibLIBRARIES:

install-pkglibLIBRARIES: $(pkglib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkglibdir)
	@list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(RANLIB) $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done

uninstall-pkglibLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(pkglib_LIBRARIES)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkglibdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libmyisam.a: $(libmyisam_a_OBJECTS) $(libmyisam_a_DEPENDENCIES)
	-rm -f libmyisam.a
	$(AR) cru libmyisam.a $(libmyisam_a_OBJECTS) $(libmyisam_a_LIBADD)
	$(RANLIB) libmyisam.a

mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

myisamchk: $(myisamchk_OBJECTS) $(myisamchk_DEPENDENCIES)
	@rm -f myisamchk
	$(LINK) $(myisamchk_LDFLAGS) $(myisamchk_OBJECTS) $(myisamchk_LDADD) $(LIBS)

myisamlog: $(myisamlog_OBJECTS) $(myisamlog_DEPENDENCIES)
	@rm -f myisamlog
	$(LINK) $(myisamlog_LDFLAGS) $(myisamlog_OBJECTS) $(myisamlog_LDADD) $(LIBS)

myisampack: $(myisampack_OBJECTS) $(myisampack_DEPENDENCIES)
	@rm -f myisampack
	$(LINK) $(myisampack_LDFLAGS) $(myisampack_OBJECTS) $(myisampack_LDADD) $(LIBS)

mi_test1: $(mi_test1_OBJECTS) $(mi_test1_DEPENDENCIES)
	@rm -f mi_test1
	$(LINK) $(mi_test1_LDFLAGS) $(mi_test1_OBJECTS) $(mi_test1_LDADD) $(LIBS)

mi_test2: $(mi_test2_OBJECTS) $(mi_test2_DEPENDENCIES)
	@rm -f mi_test2
	$(LINK) $(mi_test2_LDFLAGS) $(mi_test2_OBJECTS) $(mi_test2_LDADD) $(LIBS)

mi_test3: $(mi_test3_OBJECTS) $(mi_test3_DEPENDENCIES)
	@rm -f mi_test3
	$(LINK) $(mi_test3_LDFLAGS) $(mi_test3_OBJECTS) $(mi_test3_LDADD) $(LIBS)

ft_test1: $(ft_test1_OBJECTS) $(ft_test1_DEPENDENCIES)
	@rm -f ft_test1
	$(LINK) $(ft_test1_LDFLAGS) $(ft_test1_OBJECTS) $(ft_test1_LDADD) $(LIBS)

ft_eval: $(ft_eval_OBJECTS) $(ft_eval_DEPENDENCIES)
	@rm -f ft_eval
	$(LINK) $(ft_eval_LDFLAGS) $(ft_eval_OBJECTS) $(ft_eval_LDADD) $(LIBS)

install-pkgdataDATA: $(pkgdata_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)
	@list='$(pkgdata_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(pkgdatadir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(pkgdatadir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/$$p; \
	  fi; fi; \
	done

uninstall-pkgdataDATA:
	@$(NORMAL_UNINSTALL)
	list='$(pkgdata_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkgdatadir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = myisam

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
ft_eval.o: ft_eval.c ftdefs.h fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h ft_eval.h \
	../include/getopt.h
ft_parser.o: ft_parser.c ftdefs.h fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h
ft_search.o: ft_search.c ftdefs.h fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h
ft_static.o: ft_static.c ftdefs.h fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h
ft_stopwords.o: ft_stopwords.c ftdefs.h fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h
ft_test1.o: ft_test1.c ftdefs.h fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h ft_test1.h \
	../include/getopt.h
ft_update.o: ft_update.c ftdefs.h fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/my_tree.h
mi_cache.o: mi_cache.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_changed.o: mi_changed.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_check.o: mi_check.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/getopt.h
mi_checksum.o: mi_checksum.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_close.o: mi_close.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_create.o: mi_create.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_dbug.o: mi_dbug.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_delete.o: mi_delete.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_delete_all.o: mi_delete_all.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_delete_table.o: mi_delete_table.c fulltext.h myisamdef.h \
	../include/myisam.h ../include/my_base.h ../include/global.h \
	../include/my_config.h ../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_dynrec.o: mi_dynrec.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_extra.o: mi_extra.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_info.o: mi_info.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_key.o: mi_key.c myisamdef.h ../include/myisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_locking.o: mi_locking.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_log.o: mi_log.c myisamdef.h ../include/myisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_open.o: mi_open.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_packrec.o: mi_packrec.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_page.o: mi_page.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_panic.o: mi_panic.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_range.o: mi_range.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rename.o: mi_rename.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_rfirst.o: mi_rfirst.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rkey.o: mi_rkey.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rlast.o: mi_rlast.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rnext.o: mi_rnext.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rnext_same.o: mi_rnext_same.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rprev.o: mi_rprev.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rrnd.o: mi_rrnd.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rsame.o: mi_rsame.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_rsamepos.o: mi_rsamepos.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_scan.o: mi_scan.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_search.o: mi_search.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_static.o: mi_static.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_statrec.o: mi_statrec.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_test1.o: mi_test1.c ../include/myisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/getopt.h
mi_test2.o: mi_test2.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_test3.o: mi_test3.c ../include/myisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h
mi_unique.o: mi_unique.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h
mi_update.o: mi_update.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
mi_write.o: mi_write.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h
myisamchk.o: myisamchk.c fulltext.h myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/ft_global.h ../include/getopt.h
myisamlog.o: myisamlog.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/my_tree.h
myisampack.o: myisampack.c myisamdef.h ../include/myisam.h \
	../include/my_base.h ../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/queues.h ../include/my_tree.h ../include/mysys_err.h \
	../include/getopt.h
sort.o: sort.c myisamdef.h ../include/myisam.h ../include/my_base.h \
	../include/global.h ../include/my_config.h \
	../mit-pthreads/include/bits/local_lim.h \
	../mit-pthreads/include/endian.h ../include/dbug.h \
	../include/my_dir.h ../include/my_sys.h ../include/my_pthread.h \
	../mit-pthreads/include/pthread/config.h \
	../mit-pthreads/include/sched.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/my_list.h \
	../include/myisampack.h ../include/thr_lock.h \
	../include/queues.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-pkglibLIBRARIES install-binPROGRAMS
install-exec: install-exec-am

install-data-am: install-pkgdataDATA
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-pkglibLIBRARIES uninstall-binPROGRAMS \
		uninstall-pkgdataDATA
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(pkglibdir) $(DESTDIR)$(bindir) \
		$(DESTDIR)$(pkgdatadir)


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-pkglibLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-binPROGRAMS \
		mostlyclean-noinstPROGRAMS mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-pkglibLIBRARIES clean-compile clean-libtool \
		clean-binPROGRAMS clean-noinstPROGRAMS clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-pkglibLIBRARIES distclean-compile \
		distclean-libtool distclean-binPROGRAMS \
		distclean-noinstPROGRAMS distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-pkglibLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-binPROGRAMS \
		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-pkglibLIBRARIES distclean-pkglibLIBRARIES \
clean-pkglibLIBRARIES maintainer-clean-pkglibLIBRARIES \
uninstall-pkglibLIBRARIES install-pkglibLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-binPROGRAMS distclean-binPROGRAMS \
clean-binPROGRAMS maintainer-clean-binPROGRAMS uninstall-binPROGRAMS \
install-binPROGRAMS mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
uninstall-pkgdataDATA install-pkgdataDATA tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Move to automake rules ?
prolint:;	plparse -b -u -hF1 "-width(0,0)" "-format=%f:%l:\s%t:%n\s%m" \
		"-elib(????)" "+elib(?3??)" my.lnt $(nisam_SOURCES)

.sh:
	/usr/bin/rm -f $@ $@-t
	/usr/bin/sed \
	  -e 's!@''bindir''@!$(bindir)!g' \
	  -e 's!@''scriptdir''@!$(bindir)!g' \
	  -e 's!@''prefix''@!$(prefix)!g' \
	  -e 's!@''datadir''@!$(datadir)!g' \
	  -e 's!@''localstatedir''@!$(localstatedir)!g' \
	  -e 's!@''libexecdir''@!$(libexecdir)!g' \
	  -e 's!@''CC''@!gcc!'\
	  -e 's!@''CXX''@!c++!'\
	  -e 's!@''GXX''@!yes!'\
	  -e 's!@''PERL''@!/usr/local/bin/perl!' \
	  -e 's!@''CFLAGS''@!-m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP!'\
	  -e 's!@''CXXFLAGS''@!-m32!'\
	  -e 's!@''LDFLAGS''@!!'\
	  -e 's!@''VERSION''@!3.23.49!' \
	  -e 's!@''MYSQL_SERVER_SUFFIX''@!!' \
	  -e 's!@''COMPILATION_COMMENT''@!Source distribution!' \
	  -e 's!@''MACHINE_TYPE''@!x86_64!' \
	  -e 's!@''HOSTNAME''@!/usr/bin/hostname!' \
	  -e 's!@''SYSTEM_TYPE''@!pc-linux-gnuoldld!' \
	  -e 's!@''CHECK_PID''@!/usr/bin/kill -0 $$PID > /dev/null 2> /dev/null!' \
	  -e 's!@''FIND_PROC''@!/usr/bin/ps p $$PID | grep mysqld > /dev/null!' \
	  -e 's!@''MYSQLD_DEFAULT_SWITCHES''@!--skip-locking!' \
	  -e 's!@''MYSQL_UNIX_ADDR''@!/tmp/mysql.sock!' \
	  -e 's!@''IS_LINUX''@!true!' \
	  -e "s!@""CONF_COMMAND""@!./configure  --with-debug=yes!" \
	  -e 's!@''MYSQLD_USER''@!mysql!' \
	  -e 's!@''sysconfdir''@!${prefix}/etc!' \
	  -e 's!@''SHORT_MYSQL_INTRO''@!@SHORT_MYSQL_INTRO@!' \
	  -e 's!@''SHARED_LIB_VERSION''@!10:0:0!' \
	  -e 's!@''MYSQL_BASE_VERSION''@!3.23!' \
	  -e 's!@''MYSQL_NO_DASH_VERSION''@!3.23.49!' \
	  -e 's!@''MYSQL_TCP_PORT''@!3306!' \
	  -e 's!@''PERL_DBI_VERSION''@!@PERL_DBI_VERSION@!' \
	  -e 's!@''PERL_DBD_VERSION''@!@PERL_DBD_VERSION@!' \
	  -e 's!@''PERL_DATA_DUMPER''@!@PERL_DATA_DUMPER@!' \
	$< > $@-t
	/usr/bin/chmod +x $@-t
	/usr/bin/mv $@-t $@

# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
