# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Copyright (C) 2000 MySQL AB & MySQL Finland AB & TCX DataKonsult AB
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
# 
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
# MA 02111-1307, USA

# This file is public domain and comes with NO WARRANTY of any kind



SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = x86_64-pc-linux-gnuoldld
build_triplet = x86_64-pc-linux-gnuoldld
host_alias = x86_64-pc-linux-gnuoldld
host_triplet = x86_64-pc-linux-gnuoldld
target_alias = x86_64-pc-linux-gnuoldld
target_triplet = x86_64-pc-linux-gnuoldld
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -g -pg -ggdb3  -DDBUG_ON -DSAFE_MUTEX -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP 
CHARSETS_NEED_SOURCE =  latin1
CHARSET_SRCS = 
CHECK_PID = /usr/bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /usr/bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure  --with-debug=yes
CP = /usr/bin/cp
CPP = gcc -E
CXX = c++
CXXFLAGS = -g -pg -ggdb3  -DSAFE_MUTEX -m32  -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /usr/bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /usr/bin/hostname
IS_LINUX = true
KILL = /usr/bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /usr/bin/ln
LN_CP_F = /usr/bin/ln -s
LN_S = ln -s
MACHINE_TYPE = x86_64
MAINT = #
MAKEINFO = makeinfo
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /usr/bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.49
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32349
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/local/bin/perl
PERL5 = /usr/local/bin/perl
PROTOCOL_VERSION = 10
PS = /usr/bin/ps
RANLIB = ranlib
RM = /usr/bin/rm
SAVE_CFLAGS = -m32 -DPTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
SAVE_CXXFLAGS = -m32
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /usr/bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnuoldld
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.49
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /usr/bin/uname

target = libmysqlclient.la
target_defs = -DUNDEF_THREADS_HACK -DDONT_USE_RAID 
LIBS = -lz -lcrypt -lnsl -lm 
INCLUDES = -I$(srcdir)/../include -I../include 		-I$(srcdir)/.. -I$(top_srcdir) -I..


MYSQLDATAdir = $(localstatedir)
MYSQLSHAREdir = $(pkgdatadir)
MYSQLBASEdir = $(prefix)
LDADD =  $(target)
pkglib_LTLIBRARIES = $(target)

noinst_PROGRAMS = conf_to_src

# We need .lo, not .o files for everything.
CHARSET_OBJS = 
LTCHARSET_OBJS = ${CHARSET_OBJS:.o=.lo}

target_sources = libmysql.c net.c violite.c password.c 			    get_password.c errmsg.c


mystringsobjects = strmov.lo strxmov.lo strnmov.lo strmake.lo strend.lo 			strnlen.lo strfill.lo is_prefix.lo 			int2str.lo str2int.lo strinstr.lo strcont.lo 			strcend.lo 			bchange.lo bmove.lo bmove_upp.lo longlong2str.lo 			strtoull.lo strtoll.lo llstr.lo 			ctype.lo $(LTCHARSET_OBJS)

mystringsextra = strto.c ctype_autoconf.c
dbugobjects = dbug.lo # IT IS IN SAFEMALLOC.C sanity.lo
mysysheaders = mysys_priv.h my_static.h
mysysobjects1 = my_init.lo my_static.lo my_malloc.lo my_realloc.lo 			my_create.lo my_delete.lo mf_tempfile.lo my_open.lo 			mf_casecnv.lo my_read.lo my_write.lo errors.lo 			my_error.lo my_getwd.lo my_div.lo 			mf_pack.lo my_messnc.lo mf_dirname.lo mf_fn_ext.lo 			mf_wcomp.lo typelib.lo safemalloc.lo my_alloc.lo 			mf_format.lo mf_path.lo mf_unixpath.lo my_fopen.lo 			my_symlink.lo my_fstream.lo 			mf_loadpath.lo my_pthread.lo my_thr_init.lo 			thr_mutex.lo mulalloc.lo string.lo default.lo 			my_compress.lo array.lo my_once.lo list.lo my_net.lo                         charset.lo hash.lo mf_iocache.lo my_seek.lo 			my_pread.lo mf_cache.lo

# Not needed in the minimum library
mysysobjects2 = getopt.lo getopt1.lo getvar.lo my_lib.lo
mysysobjects = $(mysysobjects1) $(mysysobjects2)
target_libadd = $(mysysobjects) $(mystringsobjects) $(dbugobjects)
target_ldflags = -version-info 10:0:0
CLEANFILES = $(target_libadd) $(SHLIBOBJS) 			$(target)

DEFS = -DDEFAULT_CHARSET_HOME="\"$(MYSQLBASEdir)\"" 			-DDATADIR="\"$(MYSQLDATAdir)\"" 			-DSHAREDIR="\"$(MYSQLSHAREdir)\"" $(target_defs)

conf_to_src_SOURCES = conf_to_src.c
conf_to_src_LDADD = 
#force static linking of conf_to_src - essential when linking against
#custom installation of libc
conf_to_src_LDFLAGS = 

libmysqlclient_la_SOURCES = $(target_sources)
libmysqlclient_la_LIBADD = $(target_libadd)
libmysqlclient_la_LDFLAGS = $(target_ldflags)
EXTRA_DIST = Makefile.shared

# This part requires GNUmake
#
# This makes a distribution file with only the files needed to compile
# a minimal MySQL client library
#
# For a really minimal distribution (without debugging code) we could
# keep only the stubs for safemalloc.c and debug.c
#
# A list of needed headers collected from the deps information 000213
nh = global.h config-win32.h dbug.h errmsg.h global.h 		m_ctype.h m_string.h 		my_alarm.h my_config.h my_dir.h my_list.h my_net.h my_sys.h 		mysql.h mysql_com.h mysql_version.h mysqld_error.h mysys_err.h 		my_pthread.h thr_alarm.h violite.h hash.h

# Get a list of the needed objects  
lobjs = $(mysysobjects1) $(dbugobjects) $(mystringsobjects)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(pkglib_LTLIBRARIES)

CPPFLAGS = 
LDFLAGS =  -rdynamic
libmysqlclient_la_DEPENDENCIES =  my_init.lo my_static.lo my_malloc.lo \
my_realloc.lo my_create.lo my_delete.lo mf_tempfile.lo my_open.lo \
mf_casecnv.lo my_read.lo my_write.lo errors.lo my_error.lo my_getwd.lo \
my_div.lo mf_pack.lo my_messnc.lo mf_dirname.lo mf_fn_ext.lo \
mf_wcomp.lo typelib.lo safemalloc.lo my_alloc.lo mf_format.lo \
mf_path.lo mf_unixpath.lo my_fopen.lo my_symlink.lo my_fstream.lo \
mf_loadpath.lo my_pthread.lo my_thr_init.lo thr_mutex.lo mulalloc.lo \
string.lo default.lo my_compress.lo array.lo my_once.lo list.lo \
my_net.lo charset.lo hash.lo mf_iocache.lo my_seek.lo my_pread.lo \
mf_cache.lo getopt.lo getopt1.lo getvar.lo my_lib.lo strmov.lo \
strxmov.lo strnmov.lo strmake.lo strend.lo strnlen.lo strfill.lo \
is_prefix.lo int2str.lo str2int.lo strinstr.lo strcont.lo strcend.lo \
bchange.lo bmove.lo bmove_upp.lo longlong2str.lo strtoull.lo strtoll.lo \
llstr.lo ctype.lo dbug.lo
libmysqlclient_la_OBJECTS =  libmysql.lo net.lo violite.lo password.lo \
get_password.lo errmsg.lo
PROGRAMS =  $(noinst_PROGRAMS)

conf_to_src_OBJECTS =  conf_to_src.o
conf_to_src_DEPENDENCIES = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in acinclude.m4


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libmysqlclient_la_SOURCES) $(conf_to_src_SOURCES)
OBJECTS = $(libmysqlclient_la_OBJECTS) $(conf_to_src_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(srcdir)/Makefile.shared
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps libmysql/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-pkglibLTLIBRARIES:

clean-pkglibLTLIBRARIES:
	-test -z "$(pkglib_LTLIBRARIES)" || rm -f $(pkglib_LTLIBRARIES)

distclean-pkglibLTLIBRARIES:

maintainer-clean-pkglibLTLIBRARIES:

install-pkglibLTLIBRARIES: $(pkglib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkglibdir)
	@list='$(pkglib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(pkglibdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(pkglibdir)/$$p; \
	  else :; fi; \
	done

uninstall-pkglibLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(pkglib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(pkglibdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libmysqlclient.la: $(libmysqlclient_la_OBJECTS) $(libmysqlclient_la_DEPENDENCIES)
	$(LINK) -rpath $(pkglibdir) $(libmysqlclient_la_LDFLAGS) $(libmysqlclient_la_OBJECTS) $(libmysqlclient_la_LIBADD) $(LIBS)

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

conf_to_src: $(conf_to_src_OBJECTS) $(conf_to_src_DEPENDENCIES)
	@rm -f conf_to_src
	$(LINK) $(conf_to_src_LDFLAGS) $(conf_to_src_OBJECTS) $(conf_to_src_LDADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = libmysql

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
array.lo array.o : array.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
bchange.lo bchange.o : bchange.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
bmove.lo bmove.o : bmove.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_string.h
bmove_upp.lo bmove_upp.o : bmove_upp.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
charset.lo charset.o : charset.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h ../include/m_string.h \
	../include/my_dir.h
conf_to_src.o: conf_to_src.c ../include/getopt.h
ctype.lo ctype.o : ctype.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_ctype.h \
	../include/m_string.h ctype_extra_sources.c ctype_autoconf.c
dbug.lo dbug.o : dbug.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_string.h
default.lo default.o : default.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
errmsg.lo errmsg.o : errmsg.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/errmsg.h
errors.lo errors.o : errors.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h
get_password.lo get_password.o : get_password.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h ../include/m_string.h
getopt.lo getopt.o : getopt.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_string.h
getopt1.lo getopt1.o : getopt1.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h
getvar.lo getvar.o : getvar.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
hash.lo hash.o : hash.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/hash.h
int2str.lo int2str.o : int2str.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
is_prefix.lo is_prefix.o : is_prefix.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
libmysql.lo libmysql.o : libmysql.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h ../include/m_string.h ../include/mysql.h \
	../include/mysql_com.h ../include/mysql_version.h \
	../include/mysqld_error.h ../include/errmsg.h \
	../include/violite.h ../include/my_net.h
list.lo list.o : list.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/my_list.h
llstr.lo llstr.o : llstr.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_string.h
longlong2str.lo longlong2str.o : longlong2str.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
mf_cache.lo mf_cache.o : mf_cache.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h my_static.h ../include/mysys_err.h
mf_casecnv.lo mf_casecnv.o : mf_casecnv.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h
mf_dirname.lo mf_dirname.o : mf_dirname.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h
mf_fn_ext.lo mf_fn_ext.o : mf_fn_ext.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
mf_format.lo mf_format.o : mf_format.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
mf_iocache.lo mf_iocache.o : mf_iocache.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h
mf_loadpath.lo mf_loadpath.o : mf_loadpath.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h
mf_pack.lo mf_pack.o : mf_pack.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
mf_path.lo mf_path.o : mf_path.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
mf_tempfile.lo mf_tempfile.o : mf_tempfile.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h my_static.h \
	../include/mysys_err.h
mf_unixpath.lo mf_unixpath.o : mf_unixpath.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h
mf_wcomp.lo mf_wcomp.o : mf_wcomp.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h
mulalloc.lo mulalloc.o : mulalloc.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h
my_alloc.lo my_alloc.o : my_alloc.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
my_compress.lo my_compress.o : my_compress.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
my_create.lo my_create.o : my_create.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/my_dir.h ../include/mysys_err.h
my_delete.lo my_delete.o : my_delete.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h
my_div.lo my_div.o : my_div.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h
my_error.lo my_error.o : my_error.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h ../include/m_string.h
my_fopen.lo my_fopen.o : my_fopen.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	my_static.h ../include/mysys_err.h
my_fstream.lo my_fstream.o : my_fstream.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/mysys_err.h
my_getwd.lo my_getwd.o : my_getwd.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysys_err.h
my_init.lo my_init.o : my_init.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	my_static.h ../include/mysys_err.h ../include/m_string.h
my_lib.lo my_lib.o : my_lib.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/my_dir.h \
	../include/mysys_err.h
my_malloc.lo my_malloc.o : my_malloc.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h ../include/m_string.h
my_messnc.lo my_messnc.o : my_messnc.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h
my_net.lo my_net.o : my_net.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
my_once.lo my_once.o : my_once.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	my_static.h ../include/mysys_err.h
my_open.lo my_open.o : my_open.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h ../include/my_dir.h
my_pread.lo my_pread.o : my_pread.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h
my_pthread.lo my_pthread.o : my_pthread.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h
my_read.lo my_read.o : my_read.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h
my_realloc.lo my_realloc.o : my_realloc.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/mysys_err.h
my_seek.lo my_seek.o : my_seek.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h
my_static.lo my_static.o : my_static.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	my_static.h ../include/my_alarm.h
my_symlink.lo my_symlink.o : my_symlink.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/mysys_err.h ../include/m_string.h
my_thr_init.lo my_thr_init.o : my_thr_init.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h
my_write.lo my_write.o : my_write.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/mysys_err.h
net.lo net.o : net.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/violite.h \
	../include/my_net.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h ../include/mysql.h \
	../include/mysql_com.h ../include/mysql_version.h \
	../include/mysqld_error.h
password.lo password.o : password.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h ../include/mysql.h ../include/mysql_com.h \
	../include/mysql_version.h
safemalloc.lo safemalloc.o : safemalloc.c mysys_priv.h \
	../include/global.h ../include/my_config.h ../include/getopt.h \
	../include/dbug.h ../include/my_sys.h ../include/m_ctype.h \
	../include/raid.h ../include/m_string.h my_static.h \
	../include/mysys_err.h
str2int.lo str2int.o : str2int.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h ../include/m_ctype.h ../include/my_sys.h \
	../include/raid.h
strcend.lo strcend.o : strcend.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strcont.lo strcont.o : strcont.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strend.lo strend.o : strend.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_string.h
strfill.lo strfill.o : strfill.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
string.lo string.o : string.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
strinstr.lo strinstr.o : strinstr.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strmake.lo strmake.o : strmake.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strmov.lo strmov.o : strmov.c ../include/global.h ../include/my_config.h \
	../include/getopt.h ../include/dbug.h ../include/m_string.h
strnlen.lo strnlen.o : strnlen.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strnmov.lo strnmov.o : strnmov.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strtoll.lo strtoll.o : strtoll.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strtoull.lo strtoull.o : strtoull.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
strxmov.lo strxmov.o : strxmov.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
thr_mutex.lo thr_mutex.o : thr_mutex.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/m_string.h
typelib.lo typelib.o : typelib.c mysys_priv.h ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/my_sys.h ../include/m_ctype.h ../include/raid.h \
	../include/m_string.h
violite.lo violite.o : violite.c ../include/global.h \
	../include/my_config.h ../include/getopt.h ../include/dbug.h \
	../include/violite.h ../include/my_net.h ../include/my_sys.h \
	../include/m_ctype.h ../include/raid.h ../include/m_string.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-pkglibLTLIBRARIES
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-pkglibLTLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(pkglibdir)


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-pkglibLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-pkglibLTLIBRARIES clean-compile clean-libtool \
		clean-noinstPROGRAMS clean-tags clean-generic \
		mostlyclean-am clean-local

clean: clean-am

distclean-am:  distclean-pkglibLTLIBRARIES distclean-compile \
		distclean-libtool distclean-noinstPROGRAMS \
		distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-pkglibLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-pkglibLTLIBRARIES distclean-pkglibLTLIBRARIES \
clean-pkglibLTLIBRARIES maintainer-clean-pkglibLTLIBRARIES \
uninstall-pkglibLTLIBRARIES install-pkglibLTLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool mostlyclean-noinstPROGRAMS \
distclean-noinstPROGRAMS clean-noinstPROGRAMS \
maintainer-clean-noinstPROGRAMS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# The automatic dependencies miss this
bmove_upp.lo:		$(LTCHARSET_OBJS)
ctype.lo:		ctype_extra_sources.c

clean-local:
	rm -f `echo $(mystringsobjects) | sed "s;\.lo;.c;g"` \
	      `echo $(dbugobjects) | sed "s;\.lo;.c;g"` \
	      `echo $(mysysobjects) | sed "s;\.lo;.c;g"` \
	       $(mystringsextra) $(mysysheaders) ctype_extra_sources.c \
	       ../linked_client_sources

ctype_extra_sources.c: conf_to_src
	./conf_to_src $(top_srcdir)  latin1 > \
	              $(srcdir)/ctype_extra_sources.c

# Don't update the files from bitkeeper
%::SCCS/s.%

# This is called from the toplevel makefile
link_sources:
	  set -x; \
	  ss=`echo $(mystringsobjects) | sed "s;\.lo;.c;g"`; \
	  ds=`echo $(dbugobjects) | sed "s;\.lo;.c;g"`; \
	  ms=`echo $(mysysobjects) | sed "s;\.lo;.c;g"`; \
	  for f in $$ss; do \
	    rm -f $(srcdir)/$$f; \
	    /usr/bin/ln -s $(srcdir)/../strings/$$f $(srcdir)/$$f; \
	  done; \
	  for f in $(mystringsextra); do \
	    rm -f $(srcdir)/$$f; \
	    /usr/bin/ln -s $(srcdir)/../strings/$$f $(srcdir)/$$f; \
	  done; \
	  for f in $$ds; do \
	    rm -f $(srcdir)/$$f; \
	    /usr/bin/ln -s $(srcdir)/../dbug/$$f $(srcdir)/$$f; \
	  done; \
	  for f in $$ms $(mysysheaders); do \
	    rm -f $(srcdir)/$$f; \
	    /usr/bin/ln -s $(srcdir)/../mysys/$$f $(srcdir)/$$f; \
	  done;

do-lib-dist:
	dir=libmysql-$(MYSQL_NO_DASH_VERSION); \
	srcs1=`echo $(lobjs) | sed "s;\.lo;.c;g"`; \
	srcs2=$(target_sources); \
	srcs="$$srcs1 $$srcs2"; \
	objs1=`echo $(lobjs) | sed "s;\.lo;.o;g"`; \
	objs2=`echo $(target_sources) | sed "s;\.c;.o;g"`; \
	objs="$$objs1 $$objs2"; \
	rm -rf $$dir; \
	mkdir $$dir; \
	$(INSTALL_DATA) $$srcs $(mysysheaders) $$dir; \
	for i in $(nh); do $(INSTALL_DATA) ../include/$$i $$dir; done; \
	echo "# A very minimal Makefile to compile" > $$dir/Makefile; \
	echo "# the minimized libmysql library" >> $$dir/Makefile; \
	echo "# This file is autogenerated from Makefile.am" >> $$dir/Makefile; \
	echo 'CFLAGS=	-I. -DUNDEF_THREADS_HACK' >>$$dir/Makefile; \
	echo "obj=$$objs"  >>$$dir/Makefile; \
	echo 'all: libmysql.a'  >>$$dir/Makefile; \
	echo 'libmysql.a: $$(obj)'  >>$$dir/Makefile; \
	echo '	$$(AR) r $$@ $$?'  >>$$dir/Makefile; \
	gtar cvzf $$dir.tar.gz $$dir; \
	cd $$dir; gmake

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
